language: node_js
sudo: required
services:
  - docker

before_install:
  - cp sampleGlobalConstants_dev.js GlobalConstants_dev.js
  - cp sampleGlobalConstants_prod.js GlobalConstants_prod.js
  - docker build -t usaspending/usaspending-website .
  - docker run usaspending/usaspending-website -i -t --name usaspending-website

script:
  - docker exec usaspending-website -d ls

# node_js:
#   # latest in each series
#   - "6"
# # Need a C++ compiler
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8
# env:
#   - CXX=g++-4.8
# cache:
#   directories:
#     - node_modules
# before_script:
#   - cp sampleGlobalConstants_dev.js GlobalConstants_dev.js
#   - cp sampleGlobalConstants_prod.js GlobalConstants_prod.js
# script:
#   - npm run dev
#   - npm run travis
# after_success:
#   - npm install -g codeclimate-test-reporter
#   - codeclimate-test-reporter < coverage/lcov.info
# notifications:
#   email: false

# sudo: required

# langu